/** methodosQ v6 · 실제 Desktop 메뉴 기준 Framer Motion 절차 카피 */

export const LOCALES = [
  { id: "ko", label: "한국어" },
  { id: "en", label: "English" },
  { id: "zh", label: "中文" },
];

export const copy = {
  ko: {
    brand: "methodosQ",
    kicker: "Desktop · Q Methodology v6",
    heroTitle: "절차로 익히는 Q방법론 워크벤치",
    introTitle: "methodosQ 소개",
    introBody: [
      "methodosQ는 연구 초점부터 해석·결과까지 Q 연구 절차를 Desktop에서 따라가며 수행하는 학습형 워크벤치입니다.",
      "왼쪽 메뉴의 Q 연구 절차(연구 초점 → 의견장 → Q표본 → P표본 → Q-Sort → 상관·요인분석 → 그래프 → 해석·결과)를 번호 순서대로 진행합니다.",
      "예제 자료로 흐름을 익힌 뒤, 같은 메뉴 절차로 내 프로젝트를 이어 갑니다. 한국어·English UI를 지원합니다.",
      "자료는 이 컴퓨터에서만 처리됩니다(오프라인).",
    ],
    pillars: [
      { title: "Q 연구 절차", text: "8단계 메뉴로 표준화" },
      { title: "Gate 안내", text: "모자란 단계만 알려 줌" },
      { title: "예제·학습", text: "예제로 익히고 학습으로 복습" },
    ],
    ctaAnalyze: "예제·Q절차 따라가기",
    ctaLearn: "학습 메뉴 보기",
    shotNote: "실제 methodosQ 화면에서 클릭할 곳 · 번호 · 액션 자막을 따라가세요.",
    clickHint: "여기를 클릭",
    analyzeSection: {
      eyebrow: "핵심 절차 A",
      title: "예제 → Q 연구 절차",
      sub: "예제 자료 → 연구 초점 → 의견장 → Q표본 → P표본 → Q-Sort → 요인분석 → 해석·결과",
      play: "절차 재생",
      pause: "일시정지",
      replay: "처음부터",
      menuLabel: "메뉴",
    },
    learnSection: {
      eyebrow: "핵심 절차 B",
      title: "학습으로 개념 익히기",
      sub: "학습 메뉴에서 입문·연구·논문 트랙을 읽은 뒤 예제 자료로 확인합니다.",
      play: "절차 재생",
      pause: "일시정지",
      replay: "처음부터",
      menuLabel: "메뉴",
    },
    analyzeSteps: [
      { n: "01", menu: "예제 자료", title: "예제 자료 열기", action: "왼쪽 「예제 자료」를 클릭합니다", detail: "채워진 샘플로 전체 절차를 먼저 익힙니다.", shot: "./shots/a01-example.png", x: 9, y: 78, bubble: "right" },
      { n: "02", menu: "Q 연구 절차 ▸ 연구 초점", title: "연구 초점", action: "「연구 초점」에서 주제·질문을 확정합니다", detail: "포함·제외와 방법 적합성을 기록합니다.", shot: "./shots/a02-focus.png", x: 9, y: 32, bubble: "right" },
      { n: "03", menu: "Q 연구 절차 ▸ 의견장", title: "의견장(Concourse)", action: "「의견장」에서 진술을 수집·정리합니다", detail: "포화 여부를 판단하고 기록합니다.", shot: "./shots/a03-concourse.png", x: 9, y: 37, bubble: "right" },
      { n: "04", menu: "Q 연구 절차 ▸ Q표본 구성", title: "Q표본 구성", action: "「Q표본 구성」으로 진술을 정제합니다", detail: "목표 진술 수·구조화·파일럿을 반영합니다.", shot: "./shots/a04-qsample.png", x: 9, y: 42, bubble: "right" },
      { n: "05", menu: "Q 연구 절차 ▸ P표본 선정", title: "P표본 선정", action: "「P표본 선정」에서 응답자를 구성합니다", detail: "표집 기준과 인원을 맞춥니다.", shot: "./shots/a05-psample.png", x: 9, y: 47, bubble: "right" },
      { n: "06", menu: "Q 연구 절차 ▸ Q-Sort 실시", title: "Q-Sort 실시", action: "「Q-Sort 실시」로 정렬을 진행합니다", detail: "동의·비동의 분포를 보드에서 만듭니다.", shot: "./shots/a06-qsort.png", x: 9, y: 52, bubble: "right" },
      { n: "07", menu: "Q 연구 절차 ▸ 상관·요인분석", title: "상관·요인분석", action: "「상관·요인분석」을 실행합니다", detail: "요인 수·회전·설명력을 확인합니다.", shot: "./shots/a07-factor.png", x: 9, y: 57, bubble: "right" },
      { n: "08", menu: "Q 연구 절차 ▸ 그래프 결과", title: "그래프 결과", action: "「그래프 결과」에서 패턴을 봅니다", detail: "요인 구조를 시각적으로 대조합니다.", shot: "./shots/a08-charts.png", x: 9, y: 62, bubble: "right" },
      { n: "09", menu: "Q 연구 절차 ▸ 해석·결과", title: "해석·결과", action: "「해석·결과」에서 해석 문장을 작성합니다", detail: "쉬운 주석과 함께 보고 초안을 정리합니다.", shot: "./shots/a09-interpret.png", x: 9, y: 67, bubble: "right" },
    ],
    learnSteps: [
      { n: "01", menu: "학습", title: "학습 메뉴 열기", action: "왼쪽 「학습」을 클릭합니다", detail: "입문·연구중·논문대비 트랙으로 들어갑니다.", shot: "./shots/b01-learn.png", x: 9, y: 82, bubble: "right" },
      { n: "02", menu: "학습 ▸ 입문", title: "입문 트랙", action: "입문 트랙에서 기초 개념을 읽습니다", detail: "Q방법론 전체 흐름을 먼저 익힙니다.", shot: "./shots/b02-learn-intro.png", x: 42, y: 28, bubble: "bottom" },
      { n: "03", menu: "학습 ▸ 연구중", title: "연구중 트랙", action: "연구중 트랙의 실무 포인트를 확인합니다", detail: "표집·정렬·요인 단계의 주의점을 봅니다.", shot: "./shots/b03-learn-mid.png", x: 55, y: 28, bubble: "bottom" },
      { n: "04", menu: "학습 ▸ 논문대비", title: "논문대비", action: "논문대비 체크리스트를 엽니다", detail: "해석·한계·보고 문장을 점검합니다.", shot: "./shots/b04-learn-thesis.png", x: 68, y: 28, bubble: "bottom" },
      { n: "05", menu: "예제 자료", title: "예제로 확인", action: "「예제 자료」로 돌아와 학습을 검증합니다", detail: "학습 → 예제 → 내 프로젝트 순으로 이어 갑니다.", shot: "./shots/b05-example.png", x: 9, y: 78, bubble: "right" },
    ],
    footer: "© Methodos Lab · methodosQ 6",
  },
  en: {
    brand: "methodosQ",
    kicker: "Desktop · Q Methodology v6",
    heroTitle: "Learn Q methodology by procedure",
    introTitle: "About methodosQ",
    introBody: [
      "methodosQ is a desktop workbench that walks through Q research stages from focus to interpretation.",
      "Follow the left-rail Q procedure: Focus → Concourse → Q-sample → P-sample → Q-Sort → Factor analysis → Charts → Interpretation.",
      "Learn with examples, then apply the same menu path to your project. Korean · English UI.",
      "Data stays on this computer (offline).",
    ],
    pillars: [
      { title: "Q procedure", text: "Eight-stage menu" },
      { title: "Gate hints", text: "Shows what’s missing" },
      { title: "Examples · Learn", text: "Practice then apply" },
    ],
    ctaAnalyze: "Follow Q procedure",
    ctaLearn: "Open learning",
    shotNote: "Follow pin numbers and captions on the real methodosQ screen.",
    clickHint: "Click here",
    analyzeSection: {
      eyebrow: "Core path A",
      title: "Example → Q procedure",
      sub: "Examples → Focus → Concourse → Q-sample → P-sample → Q-Sort → Factors → Interpretation",
      play: "Play steps",
      pause: "Pause",
      replay: "Replay",
      menuLabel: "Menu",
    },
    learnSection: {
      eyebrow: "Core path B",
      title: "Learn concepts",
      sub: "Open Learn tracks, then verify with Examples.",
      play: "Play steps",
      pause: "Pause",
      replay: "Replay",
      menuLabel: "Menu",
    },
    analyzeSteps: [
      { n: "01", menu: "Examples", title: "Open examples", action: "Click Examples in the left rail", detail: "Start with a filled sample project.", shot: "./shots/a01-example.png", x: 9, y: 78, bubble: "right" },
      { n: "02", menu: "Procedure ▸ Focus", title: "Research focus", action: "Open Research focus", detail: "Confirm topic, question, and fit.", shot: "./shots/a02-focus.png", x: 9, y: 32, bubble: "right" },
      { n: "03", menu: "Procedure ▸ Concourse", title: "Concourse", action: "Collect and organize statements", detail: "Judge and record saturation.", shot: "./shots/a03-concourse.png", x: 9, y: 37, bubble: "right" },
      { n: "04", menu: "Procedure ▸ Q-sample", title: "Q-sample", action: "Refine the Q-sample", detail: "Target size, structure, pilot.", shot: "./shots/a04-qsample.png", x: 9, y: 42, bubble: "right" },
      { n: "05", menu: "Procedure ▸ P-sample", title: "P-sample", action: "Select the P-sample", detail: "Set sampling criteria and size.", shot: "./shots/a05-psample.png", x: 9, y: 47, bubble: "right" },
      { n: "06", menu: "Procedure ▸ Q-Sort", title: "Q-Sort", action: "Run Q-Sort", detail: "Build agree/disagree distributions.", shot: "./shots/a06-qsort.png", x: 9, y: 52, bubble: "right" },
      { n: "07", menu: "Procedure ▸ Factors", title: "Factor analysis", action: "Run correlation & factor analysis", detail: "Check factor count and rotation.", shot: "./shots/a07-factor.png", x: 9, y: 57, bubble: "right" },
      { n: "08", menu: "Procedure ▸ Charts", title: "Chart results", action: "Open chart results", detail: "Compare factor patterns visually.", shot: "./shots/a08-charts.png", x: 9, y: 62, bubble: "right" },
      { n: "09", menu: "Procedure ▸ Interpretation", title: "Interpretation", action: "Write interpretation notes", detail: "Draft reporting with plain notes.", shot: "./shots/a09-interpret.png", x: 9, y: 67, bubble: "right" },
    ],
    learnSteps: [
      { n: "01", menu: "Learn", title: "Open Learn", action: "Click Learn in the left rail", detail: "Enter intro / research / thesis tracks.", shot: "./shots/b01-learn.png", x: 9, y: 82, bubble: "right" },
      { n: "02", menu: "Learn ▸ Intro", title: "Intro track", action: "Read the intro track", detail: "Learn the overall Q flow first.", shot: "./shots/b02-learn-intro.png", x: 42, y: 28, bubble: "bottom" },
      { n: "03", menu: "Learn ▸ In research", title: "In-research", action: "Check practical tips", detail: "Sorting and factor caveats.", shot: "./shots/b03-learn-mid.png", x: 55, y: 28, bubble: "bottom" },
      { n: "04", menu: "Learn ▸ Thesis", title: "Thesis prep", action: "Open the thesis checklist", detail: "Interpretation and reporting checks.", shot: "./shots/b04-learn-thesis.png", x: 68, y: 28, bubble: "bottom" },
      { n: "05", menu: "Examples", title: "Verify with example", action: "Return to Examples to verify", detail: "Learn → example → your project.", shot: "./shots/b05-example.png", x: 9, y: 78, bubble: "right" },
    ],
    footer: "© Methodos Lab · methodosQ 6",
  },
  zh: {
    brand: "methodosQ",
    kicker: "Desktop · Q方法 v6",
    heroTitle: "按步骤掌握 Q 方法工作台",
    introTitle: "methodosQ 简介",
    introBody: [
      "methodosQ 在桌面端按 Q 研究阶段（从研究焦点到解释·结果）引导操作。",
      "左侧菜单：研究焦点 → 意见场 → Q样本 → P样本 → Q-Sort → 相关·因子分析 → 图表 → 解释·结果。",
      "先用示例熟悉流程，再用相同菜单路径做自己的项目。支持韩语·English。",
      "数据仅在本机处理（离线）。",
    ],
    pillars: [
      { title: "Q 研究程序", text: "八阶段菜单" },
      { title: "Gate 提示", text: "只提示缺什么" },
      { title: "示例·学习", text: "先练后用" },
    ],
    ctaAnalyze: "跟随 Q 程序",
    ctaLearn: "打开学习",
    shotNote: "请跟随 methodosQ 实际画面上的编号与字幕。",
    clickHint: "点击这里",
    analyzeSection: {
      eyebrow: "核心流程 A",
      title: "示例 → Q 研究程序",
      sub: "示例 → 焦点 → 意见场 → Q样本 → P样本 → Q-Sort → 因子 → 解释",
      play: "播放步骤",
      pause: "暂停",
      replay: "重播",
      menuLabel: "菜单",
    },
    learnSection: {
      eyebrow: "核心流程 B",
      title: "学习概念",
      sub: "在学习轨道阅读后，用示例验证。",
      play: "播放步骤",
      pause: "暂停",
      replay: "重播",
      menuLabel: "菜单",
    },
    analyzeSteps: [
      { n: "01", menu: "示例资料", title: "打开示例", action: "点击左侧「示例资料」", detail: "先用已填充示例熟悉全流程。", shot: "./shots/a01-example.png", x: 9, y: 78, bubble: "right" },
      { n: "02", menu: "程序 ▸ 研究焦点", title: "研究焦点", action: "在「研究焦点」确定主题与问题", detail: "记录纳入/排除与方法适合性。", shot: "./shots/a02-focus.png", x: 9, y: 32, bubble: "right" },
      { n: "03", menu: "程序 ▸ 意见场", title: "意见场", action: "在「意见场」收集并整理陈述", detail: "判断并记录是否饱和。", shot: "./shots/a03-concourse.png", x: 9, y: 37, bubble: "right" },
      { n: "04", menu: "程序 ▸ Q样本", title: "Q样本", action: "精炼 Q 样本", detail: "目标数量、结构化、预试。", shot: "./shots/a04-qsample.png", x: 9, y: 42, bubble: "right" },
      { n: "05", menu: "程序 ▸ P样本", title: "P样本", action: "选定 P 样本", detail: "匹配抽样标准与人数。", shot: "./shots/a05-psample.png", x: 9, y: 47, bubble: "right" },
      { n: "06", menu: "程序 ▸ Q-Sort", title: "Q-Sort", action: "实施 Q-Sort", detail: "在排序板上形成分布。", shot: "./shots/a06-qsort.png", x: 9, y: 52, bubble: "right" },
      { n: "07", menu: "程序 ▸ 因子分析", title: "相关·因子", action: "运行相关与因子分析", detail: "确认因子数与旋转。", shot: "./shots/a07-factor.png", x: 9, y: 57, bubble: "right" },
      { n: "08", menu: "程序 ▸ 图表", title: "图表结果", action: "查看图表结果", detail: "对照因子结构。", shot: "./shots/a08-charts.png", x: 9, y: 62, bubble: "right" },
      { n: "09", menu: "程序 ▸ 解释", title: "解释·结果", action: "撰写解释文案", detail: "结合浅显注释整理报告草稿。", shot: "./shots/a09-interpret.png", x: 9, y: 67, bubble: "right" },
    ],
    learnSteps: [
      { n: "01", menu: "学习", title: "打开学习", action: "点击左侧「学习」", detail: "进入入门/研究/论文轨道。", shot: "./shots/b01-learn.png", x: 9, y: 82, bubble: "right" },
      { n: "02", menu: "学习 ▸ 入门", title: "入门", action: "阅读入门轨道", detail: "先掌握整体流程。", shot: "./shots/b02-learn-intro.png", x: 42, y: 28, bubble: "bottom" },
      { n: "03", menu: "学习 ▸ 研究中", title: "研究中", action: "查看实务要点", detail: "排序与因子注意点。", shot: "./shots/b03-learn-mid.png", x: 55, y: 28, bubble: "bottom" },
      { n: "04", menu: "学习 ▸ 论文", title: "论文准备", action: "打开论文清单", detail: "检查解释与报告。", shot: "./shots/b04-learn-thesis.png", x: 68, y: 28, bubble: "bottom" },
      { n: "05", menu: "示例资料", title: "用示例验证", action: "回到示例资料验证", detail: "学习 → 示例 → 自己的项目。", shot: "./shots/b05-example.png", x: 9, y: 78, bubble: "right" },
    ],
    footer: "© Methodos Lab · methodosQ 6",
  },
};
