/** ko / en / zh — 소개 + 실제 화면 클릭 핫스팟 절차 */

export const LOCALES = [
  { id: "ko", label: "한국어" },
  { id: "en", label: "English" },
  { id: "zh", label: "中文" },
];

/**
 * hotspot: 화면 위 클릭 위치 (%). bubble: 자막 위치 (left|right|top|bottom)
 * action: 클릭 옆 자막 — “무슨 액션인지”
 * 번호는 핀에만 표시 (말풍선·하단 바 중복 번호 없음)
 */
export const copy = {
  ko: {
    brand: "Methodos Basic",
    kicker: "연구용 통계 · LT-4-all-v3",
    heroTitle: "절차로 익히는 연구용 통계",
    introTitle: "Methodos Basic 소개",
    introBody: [
      "Methodos Basic은 분석을 도와주는 자동화 프로그램입니다. 다만 결과만 넘겨 주는 데 그치지 않고, 통계의 절차와 의미를 단계적으로 따라가며 이해도를 높이도록 설계했습니다.",
      "연구 목적에 맞는 기법을 고르고, 예제·학습 가이드로 개념을 익힌 뒤, 자료를 보고 변수를 배정하며 분석·그래프·결과 해석까지 같은 흐름으로 진행합니다.",
      "쉬운 말과 주석으로 이해를 돕고, 한국어·English·中文 전환으로 영어권·중국어권 해외 유학생도 같은 절차로 배울 수 있습니다.",
      "자료는 이 컴퓨터에서만 처리됩니다(오프라인).",
    ],
    pillars: [
      { title: "개념 중심", text: "왜 이 기법인지부터 묻습니다" },
      { title: "쉬운 주석", text: "결과·옵션을 평이한 말로 풉니다" },
      { title: "한 · 영 · 중", text: "해외 학습자도 같은 절차" },
    ],
    ctaAnalyze: "예제로 분석하기",
    ctaLearn: "학습 절차 보기",
    shotNote: "실제 화면에서 클릭할 곳 · 번호 · 액션 자막을 따라가세요. (번호는 클릭 핀에만 표시)",
    clickHint: "여기를 클릭",
    analyzeSection: {
      eyebrow: "핵심 절차 A",
      title: "예제를 통한 분석",
      sub: "예제 자료(D10) 불러오기 → 기술통계 선택 → 변수 넣기·척도 맞추기 → 분석 실행 → 그래프·결과 확인 → (추가) 사용자 파일 불러오기",
      play: "절차 재생",
      pause: "일시정지",
      replay: "처음부터",
      menuLabel: "메뉴",
    },
    learnSection: {
      eyebrow: "핵심 절차 B",
      title: "학습으로 통계 익히기",
      sub: "학습 메뉴에서 명칭 → 초·중·고급을 읽고, 라이브러리 예제로 확인한 뒤 작업대에 적용합니다.",
      play: "절차 재생",
      pause: "일시정지",
      replay: "처음부터",
      menuLabel: "메뉴",
    },
    analyzeSteps: [
      {
        n: "01",
        menu: "예제 자료 ▸ 자료 목록",
        title: "예제 고르기",
        action: "목록에서 「D10_생존_중도탈락_2400」을 선택합니다",
        detail: "사례·변수·상황을 먼저 확인합니다.",
        shot: "./shots/a01-pick-d10.png",
        x: 22,
        y: 48,
        bubble: "right",
      },
      {
        n: "02",
        menu: "예제 자료 ▸ 이 자료 불러오기",
        title: "자료 불러오기",
        action: "「이 자료 불러오기」를 클릭합니다",
        detail: "선택 자료가 통계 계산 화면으로 넘어갑니다.",
        shot: "./shots/a02-load.png",
        x: 55,
        y: 28,
        bubble: "left",
      },
      {
        n: "03",
        menu: "통계 계산 ▸ 기술통계",
        title: "분석기법 선택",
        action: "계산할 기법에서 「기술통계」를 클릭합니다",
        detail: "다른 기법도 같은 순서로 진행합니다.",
        shot: "./shots/a03-method.png",
        x: 42,
        y: 40,
        bubble: "left",
      },
      {
        n: "04",
        menu: "통계 계산 ▸ 자료",
        title: "불러온 자료 확인",
        action: "왼쪽 「자료」를 눌러 D10 변수를 봅니다",
        detail: "학생ID·성별·SES·초기성취·중도탈락 등이 나타납니다.",
        shot: "./shots/a04-data-tab.png",
        x: 22,
        y: 14,
        bubble: "bottom",
      },
      {
        n: "05",
        menu: "통계 계산 ▸ 변수 넣기",
        title: "변수 칸 열기",
        action: "오른쪽에서 「변수 넣기」를 클릭합니다",
        detail: "「변수 고르는 중…」으로 바뀌고, 위에 허용 척도(continuous/integer/categorical/binary/count/text)가 표시됩니다.",
        shot: "./shots/a05-put-var.png",
        x: 86,
        y: 48,
        bubble: "left",
      },
      {
        n: "06",
        menu: "통계 계산 ▸ 변수 선택",
        title: "척도에 맞게 고르기",
        action: "척도와 맞는 변수(예: SES·성별·중도탈락)를 클릭해 칸에 넣습니다",
        detail: "문자형·범주형·연속형·이분형 안내를 보고 선택합니다.",
        shot: "./shots/a06-pick-var.png",
        x: 22,
        y: 55,
        bubble: "right",
      },
      {
        n: "07",
        menu: "통계 계산 ▸ 분석 실행",
        title: "분석 실행",
        action: "설정에서 「분석 실행」을 클릭합니다",
        detail: "결과 수치와 그래프가 통계 계산 화면에 나타납니다.",
        shot: "./shots/a07-run.png",
        x: 86,
        y: 88,
        bubble: "left",
      },
      {
        n: "08",
        menu: "그래프 그리기",
        title: "그래프 확인",
        action: "왼쪽 「그래프 그리기」로 그림을 확인합니다",
        detail: "패턴을 더 정확히 읽습니다.",
        shot: "./shots/a08-charts.png",
        x: 8.2,
        y: 59,
        bubble: "right",
      },
      {
        n: "09",
        menu: "통계분석결과",
        title: "결과 해석",
        action: "「통계분석결과」에서 표·해석을 엽니다",
        detail: "쉬운 해석 문장과 표를 함께 읽습니다.",
        shot: "./shots/a09-results.png",
        x: 8.2,
        y: 65,
        bubble: "right",
      },
      {
        n: "10",
        menu: "파일 ▸ 데이터 파일 불러오기",
        title: "사용자 자료로 이어가기",
        action: "추가로 「파일 → 데이터 파일 불러오기」로 사용자 자료를 연 뒤 같은 순서로 분석합니다",
        detail: "예제와 동일한 절차로 실행하면 됩니다.",
        shot: "./shots/a10-file-open.png",
        x: 8,
        y: 8,
        bubble: "bottom",
      },
    ],
    learnSteps: [
      {
        n: "01",
        menu: "학습 ▸ 명칭학습",
        title: "명칭 익히기",
        action: "「명칭학습」탭을 클릭합니다",
        detail: "기법 이름·코드·한 줄 요약을 먼저 익힙니다.",
        shot: "./shots/b01-learn-names.png",
        x: 24,
        y: 19,
        bubble: "bottom",
      },
      {
        n: "02",
        menu: "학습 ▸ 초급",
        title: "초급 절차",
        action: "「초급」탭을 클릭합니다",
        detail: "요약·비교 등 기초 절차를 읽습니다.",
        shot: "./shots/b02-learn-beginner.png",
        x: 38,
        y: 19,
        bubble: "bottom",
      },
      {
        n: "03",
        menu: "학습 ▸ 중급",
        title: "중급 절차",
        action: "「중급」탭을 클릭합니다",
        detail: "회귀·분산분석 확장을 따라갑니다.",
        shot: "./shots/b03-learn-mid.png",
        x: 52,
        y: 19,
        bubble: "bottom",
      },
      {
        n: "04",
        menu: "학습 ▸ 고급",
        title: "고급 절차",
        action: "「고급」탭을 클릭합니다",
        detail: "잠재·다층·종단·생존 등 심화 개념을 익힙니다.",
        shot: "./shots/b04-learn-adv.png",
        x: 66,
        y: 19,
        bubble: "bottom",
      },
      {
        n: "05",
        menu: "통계방법 라이브러리",
        title: "예제로 확인",
        action: "「통계방법 라이브러리」에서 배운 기법을 예제로 확인합니다",
        detail: "개념을 화면에서 바로 검증합니다.",
        shot: "./shots/b05-library.png",
        x: 8.2,
        y: 32.5,
        bubble: "right",
      },
      {
        n: "06",
        menu: "통계분석작업하기",
        title: "작업대에 적용",
        action: "「통계분석작업하기」로 돌아와 같은 절차를 적용합니다",
        detail: "학습한 흐름을 사용자 자료·예제에 옮깁니다.",
        shot: "./shots/b06-analysis.png",
        x: 8.2,
        y: 51,
        bubble: "right",
      },
    ],
    footer: "© Methodos Lab",
  },
  en: {
    brand: "Methodos Basic",
    kicker: "Research statistics · LT-4-all-v3",
    heroTitle: "Learn research statistics by procedure",
    introTitle: "About Methodos Basic",
    introBody: [
      "Methodos Basic is an automation tool that assists analysis — but it does not stop at handing you numbers. It is designed so you follow statistical procedures step by step and deepen your understanding of what the results mean.",
      "You choose a method for your research aim, learn concepts through examples and guides, then view data, assign variables, and move through analysis → charts → interpretation on the same path.",
      "Plain language and annotations support learning. Korean · English · 中文 switching lets English- and Chinese-speaking international students follow the same procedures.",
      "Data is processed only on this computer (offline).",
    ],
    pillars: [
      { title: "Concept-first", text: "Start with why this method" },
      { title: "Plain notes", text: "Results in simple words" },
      { title: "KO · EN · ZH", text: "Same path for internationals" },
    ],
    ctaAnalyze: "Analyze with examples",
    ctaLearn: "See learning path",
    shotNote: "Follow the click pin number and action caption on the real screen. (Numbers appear only on the pin.)",
    clickHint: "Click here",
    analyzeSection: {
      eyebrow: "Core path A",
      title: "Analysis through examples",
      sub: "Load example D10 → pick Descriptive stats → add variables by scale → run → charts/results → (optional) open your file the same way.",
      play: "Play steps",
      pause: "Pause",
      replay: "Replay",
      menuLabel: "Menu",
    },
    learnSection: {
      eyebrow: "Core path B",
      title: "Learn statistics by studying",
      sub: "Follow Names → Beginner–Advanced, verify in the library, then apply on the workbench.",
      play: "Play steps",
      pause: "Pause",
      replay: "Replay",
      menuLabel: "Menu",
    },
    analyzeSteps: [
      { n: "01", menu: "Examples ▸ List", title: "Pick an example", action: "Select D10_survival_dropout_2400 in the list", detail: "Check cases, variables, and situation first.", shot: "./shots/a01-pick-d10.png", x: 22, y: 48, bubble: "right" },
      { n: "02", menu: "Examples ▸ Load", title: "Load data", action: "Click Load this dataset", detail: "The file opens on the Run analysis screen.", shot: "./shots/a02-load.png", x: 55, y: 28, bubble: "left" },
      { n: "03", menu: "Run analysis ▸ Descriptive", title: "Pick a method", action: "Click Descriptive statistics in the method list", detail: "Other methods follow the same path.", shot: "./shots/a03-method.png", x: 42, y: 40, bubble: "left" },
      { n: "04", menu: "Run analysis ▸ Data", title: "View loaded data", action: "Click Data on the left to see D10 variables", detail: "IDs, SES, outcomes, dropout flags appear.", shot: "./shots/a04-data-tab.png", x: 22, y: 14, bubble: "bottom" },
      { n: "05", menu: "Run analysis ▸ Add variable", title: "Open a slot", action: "Click Add variable on the right", detail: "It switches to Picking variables… and shows allowed scales.", shot: "./shots/a05-put-var.png", x: 86, y: 48, bubble: "left" },
      { n: "06", menu: "Run analysis ▸ Assign", title: "Match scales", action: "Click variables that match the scale (e.g. SES, gender, dropout)", detail: "Use text/categorical/continuous/binary cues.", shot: "./shots/a06-pick-var.png", x: 22, y: 55, bubble: "right" },
      { n: "07", menu: "Run analysis ▸ Run", title: "Run", action: "In Settings, click Run analysis", detail: "Numbers and charts appear on the results pane.", shot: "./shots/a07-run.png", x: 86, y: 88, bubble: "left" },
      { n: "08", menu: "Charts", title: "Charts", action: "Open Charts in the left rail", detail: "Read figure patterns more carefully.", shot: "./shots/a08-charts.png", x: 8.5, y: 60, bubble: "right" },
      { n: "09", menu: "Results", title: "Results", action: "Open Results for tables and notes", detail: "Read plain-language interpretation.", shot: "./shots/a09-results.png", x: 8.5, y: 66, bubble: "right" },
      { n: "10", menu: "File ▸ Open data", title: "User data", action: "Optionally File → Open data file… to open user data, then repeat the same steps", detail: "Same procedure as the example.", shot: "./shots/a10-file-open.png", x: 8, y: 8, bubble: "bottom" },
    ],
    learnSteps: [
      { n: "01", menu: "Learn ▸ Names", title: "Method names", action: "Click the Method names tab", detail: "Learn names and codes first.", shot: "./shots/b01-learn-names.png", x: 22, y: 20, bubble: "bottom" },
      { n: "02", menu: "Learn ▸ Beginner", title: "Beginner", action: "Click the Beginner tab", detail: "Follow summary/compare guides.", shot: "./shots/b02-learn-beginner.png", x: 38, y: 20, bubble: "bottom" },
      { n: "03", menu: "Learn ▸ Intermediate", title: "Intermediate", action: "Click the Intermediate tab", detail: "Build regression/ANOVA extensions.", shot: "./shots/b03-learn-mid.png", x: 52, y: 20, bubble: "bottom" },
      { n: "04", menu: "Learn ▸ Advanced", title: "Advanced", action: "Click the Advanced tab", detail: "Latent, multilevel, longitudinal, survival.", shot: "./shots/b04-learn-adv.png", x: 66, y: 20, bubble: "bottom" },
      { n: "05", menu: "Method library", title: "Verify with example", action: "Open the library and confirm with an example", detail: "Check what you learned on screen.", shot: "./shots/b05-library.png", x: 8.5, y: 33, bubble: "right" },
      { n: "06", menu: "Workbench", title: "Apply", action: "Return to Analysis workbench and apply the same path", detail: "Move learning onto your data.", shot: "./shots/b06-analysis.png", x: 8.5, y: 52, bubble: "right" },
    ],
    footer: "© Methodos Lab",
  },
  zh: {
    brand: "Methodos Basic",
    kicker: "研究用统计 · LT-4-all-v3",
    heroTitle: "按步骤掌握研究用统计",
    introTitle: "Methodos Basic 简介",
    introBody: [
      "Methodos Basic 是协助分析的自动化程序，但不止于交出结果。它按统计步骤引导操作，帮助你循序提高对概念与含义的理解。",
      "按研究目的选择方法，通过示例与学习指南建立概念，再查看数据、分配变量，并按 分析 → 图表 → 结果解读 的同一流程进行。",
      "用浅显语言与注释帮助理解，并支持 한국어 · English · 中文，方便英语区与中文区（含留学生）按同一流程学习。",
      "数据仅在本机处理（离线）。",
    ],
    pillars: [
      { title: "概念为本", text: "先问为何用此法" },
      { title: "浅显注释", text: "用平实语言读结果" },
      { title: "韩 · 英 · 中", text: "留学生同一流程" },
    ],
    ctaAnalyze: "用示例分析",
    ctaLearn: "查看学习流程",
    shotNote: "请跟随实际画面上的点击编号与操作字幕。（编号仅显示在点击图钉上）",
    clickHint: "点击这里",
    analyzeSection: {
      eyebrow: "核心流程 A",
      title: "通过示例进行分析",
      sub: "加载示例 D10 → 选择描述统计 → 按尺度放入变量 → 运行 → 图表/结果 →（可选）用同样步骤打开自己的文件。",
      play: "播放步骤",
      pause: "暂停",
      replay: "重播",
      menuLabel: "菜单",
    },
    learnSection: {
      eyebrow: "核心流程 B",
      title: "通过学习掌握统计",
      sub: "名称 → 初中高级，在方法库验证，再回到工作台应用。",
      play: "播放步骤",
      pause: "暂停",
      replay: "重播",
      menuLabel: "菜单",
    },
    analyzeSteps: [
      { n: "01", menu: "示例数据 ▸ 列表", title: "选择示例", action: "在列表中选择 D10_生存_中途脱落_2400", detail: "先确认个案、变量与情境。", shot: "./shots/a01-pick-d10.png", x: 22, y: 48, bubble: "right" },
      { n: "02", menu: "示例数据 ▸ 加载", title: "加载数据", action: "点击「加载此数据」", detail: "文件会进入统计计算界面。", shot: "./shots/a02-load.png", x: 55, y: 28, bubble: "left" },
      { n: "03", menu: "统计计算 ▸ 描述统计", title: "选择方法", action: "在可计算方法中点击「描述统计」", detail: "其他方法也按同一顺序。", shot: "./shots/a03-method.png", x: 42, y: 40, bubble: "left" },
      { n: "04", menu: "统计计算 ▸ 数据", title: "查看已加载数据", action: "点击左侧「数据」查看 D10 变量", detail: "会显示 ID、SES、结果、脱落等。", shot: "./shots/a04-data-tab.png", x: 22, y: 14, bubble: "bottom" },
      { n: "05", menu: "统计计算 ▸ 放入变量", title: "打开栏位", action: "在右侧点击「放入变量」", detail: "变为「正在选择变量…」，并显示允许的尺度类型。", shot: "./shots/a05-put-var.png", x: 86, y: 48, bubble: "left" },
      { n: "06", menu: "统计计算 ▸ 选择变量", title: "按尺度选择", action: "点击与尺度相符的变量（如 SES、性别、脱落）", detail: "按字符/类别/连续/二分提示选择。", shot: "./shots/a06-pick-var.png", x: 22, y: 55, bubble: "right" },
      { n: "07", menu: "统计计算 ▸ 运行", title: "运行分析", action: "在设置中点击「运行分析」", detail: "结果数值与图表会出现在界面中。", shot: "./shots/a07-run.png", x: 86, y: 88, bubble: "left" },
      { n: "08", menu: "绘制图表", title: "查看图表", action: "点击左侧「绘制图表」", detail: "更仔细阅读图形模式。", shot: "./shots/a08-charts.png", x: 8.5, y: 60, bubble: "right" },
      { n: "09", menu: "统计分析结果", title: "查看结果", action: "打开「统计分析结果」查看表与解说", detail: "结合浅显解说阅读。", shot: "./shots/a09-results.png", x: 8.5, y: 66, bubble: "right" },
      { n: "10", menu: "文件 ▸ 打开数据", title: "用户数据", action: "可选：文件 → 打开数据文件… 打开用户数据后，再按同样步骤分析", detail: "与示例流程相同。", shot: "./shots/a10-file-open.png", x: 8, y: 8, bubble: "bottom" },
    ],
    learnSteps: [
      { n: "01", menu: "学习 ▸ 名称", title: "名称学习", action: "点击「名称学习」标签", detail: "先熟悉方法名称与代码。", shot: "./shots/b01-learn-names.png", x: 22, y: 20, bubble: "bottom" },
      { n: "02", menu: "学习 ▸ 初级", title: "初级", action: "点击「初级」标签", detail: "阅读汇总·比较指南。", shot: "./shots/b02-learn-beginner.png", x: 38, y: 20, bubble: "bottom" },
      { n: "03", menu: "学习 ▸ 中级", title: "中级", action: "点击「中级」标签", detail: "跟随回归·方差分析扩展。", shot: "./shots/b03-learn-mid.png", x: 52, y: 20, bubble: "bottom" },
      { n: "04", menu: "学习 ▸ 高级", title: "高级", action: "点击「高级」标签", detail: "潜变量、多层、纵向、生存。", shot: "./shots/b04-learn-adv.png", x: 66, y: 20, bubble: "bottom" },
      { n: "05", menu: "统计方法库", title: "用示例验证", action: "打开方法库并用示例确认", detail: "在画面上验证所学。", shot: "./shots/b05-library.png", x: 8.5, y: 33, bubble: "right" },
      { n: "06", menu: "分析工作台", title: "回到工作台", action: "回到「分析工作台」应用同一流程", detail: "把学习迁移到自己的数据。", shot: "./shots/b06-analysis.png", x: 8.5, y: 52, bubble: "right" },
    ],
    footer: "© Methodos Lab",
  },
};
