/** methodosG v6 · 예제 자료 기준 Framer Motion 절차 카피 */

export const LOCALES = [
  { id: "ko", label: "한국어" },
  { id: "en", label: "English" },
  { id: "zh", label: "中文" },
];

export const copy = {
  ko: {
    brand: "methodosG",
    kicker: "Desktop · 근거이론 v6",
    heroTitle: "예제로 익히는 근거이론 워크벤치",
    introTitle: "methodosG 소개",
    introBody: [
      "methodosG는 근거이론의 코딩·범주화·이론화 절차를 Desktop에서 따라가며 수행하는 분석 워크벤치입니다.",
      "「예제 자료」로 다문화 가족 사례를 연 뒤, 연구 절차 메뉴(문제 설정 → 근거자료 → 의미추출 → 범주연결 → 이론응축 → 결과 그래프 → 이론 결과)를 번호 순으로 진행합니다.",
      "각 단계의 「예시 문장 넣기」로 채움 예시를 확인한 다음, 같은 메뉴로 내 프로젝트를 이어 갑니다. 자료는 이 컴퓨터에서만 처리됩니다(오프라인).",
    ],
    pillars: [
      { title: "예제 → 코딩", text: "예제 자료·개방·축·선택" },
      { title: "이론화 → 보고", text: "그래프·이론 결과·내보내기" },
      { title: "로컬 우선", text: "오프라인 · PC에 저장" },
    ],
    ctaAnalyze: "예제 → 코딩 따라가기",
    ctaLearn: "이론화 → 보고 보기",
    shotNote: "실제 methodosG 화면(예제 자료 채움)에서 클릭할 곳 · 번호 · 액션 자막을 따라가세요.",
    clickHint: "여기를 클릭",
    analyzeSection: {
      eyebrow: "핵심 절차 A",
      title: "예제 → 코딩",
      sub: "예제 자료 → 문제 설정 → 근거자료 → 의미추출 → 범주연결 → 이론응축",
      play: "절차 재생",
      pause: "일시정지",
      replay: "처음부터",
      menuLabel: "메뉴",
    },
    learnSection: {
      eyebrow: "핵심 절차 B",
      title: "이론화 → 보고",
      sub: "결과 그래프 → 이론 결과 → 절차형 실습 → 홈 진행 → 논문형 결과",
      play: "절차 재생",
      pause: "일시정지",
      replay: "처음부터",
      menuLabel: "메뉴",
    },
    analyzeSteps: [
      {
        n: "01",
        menu: "학습·설정 ▸ 예제 자료",
        title: "예제 자료 열기",
        action: "왼쪽 「예제 자료」에서 사례 카드를 고릅니다",
        detail: "다문화 가족의 제도 이용 경험 형성 등 채워진 샘플로 전체 절차를 먼저 익힙니다.",
        shot: "./shots/a01-example.png", x: 8.5, y: 87, bubble: "right",
      },
      {
        n: "02",
        menu: "홈 ▸ 예제로 흐름 익히기",
        title: "예제 흐름 시작",
        action: "홈의 「예제로 흐름 익히기」로 들어갑니다",
        detail: "현재 진행(약 91%)을 확인하며 예제 프로젝트로 이어집니다.",
        shot: "./shots/a00-home.png", x: 36, y: 31, bubble: "bottom",
      },
      {
        n: "03",
        menu: "연구 절차 ▸ 문제 설정",
        title: "문제 감각 정리",
        action: "「문제 설정」에서 주제를 확인합니다",
        detail: "예제: 다문화 가족의 제도 이용 경험 형성.",
        shot: "./shots/a00-problem.png", x: 8.5, y: 44, bubble: "right",
      },
      {
        n: "04",
        menu: "연구 절차 ▸ 근거자료",
        title: "자료원 목록",
        action: "「근거자료」에서 자료원 매트릭스를 봅니다",
        detail: "예제: 다현장 관찰 + 이해관계자 면담.",
        shot: "./shots/a01-load.png", x: 8.5, y: 49.5, bubble: "right",
      },
      {
        n: "05",
        menu: "연구 절차 ▸ 의미추출",
        title: "개방 코딩",
        action: "「의미추출」에서 의미 분절·코드를 부착합니다",
        detail: "「예시 문장 넣기」로 원문 발췌 예시를 채울 수 있습니다.",
        shot: "./shots/a02-open.png", x: 8.5, y: 55, bubble: "right",
      },
      {
        n: "06",
        menu: "연구 절차 ▸ 범주연결",
        title: "축 코딩",
        action: "「범주연결」에서 초점 코딩·관계를 묶습니다",
        detail: "예제 코드: 조건_촉발 · 전략_대응 · 결과_재배치.",
        shot: "./shots/a03-axial.png", x: 8.5, y: 60.5, bubble: "right",
      },
      {
        n: "07",
        menu: "연구 절차 ▸ 이론응축",
        title: "선택 코딩",
        action: "「이론응축」에서 핵심 범주를 확정합니다",
        detail: "예제 핵심범주: 실천의 국소적 발명.",
        shot: "./shots/a04-selective.png", x: 8.5, y: 66.5, bubble: "right",
      },
    ],
    learnSteps: [
      {
        n: "01",
        menu: "연구 절차 ▸ 결과 그래프",
        title: "코드 빈도 그래프",
        action: "「결과 그래프」에서 코드 빈도를 확인합니다",
        detail: "예제 코드 막대(조건_촉발 등)로 포화·커버리지를 봅니다.",
        shot: "./shots/a05-graphs.png", x: 8.5, y: 72.5, bubble: "right",
      },
      {
        n: "02",
        menu: "연구 절차 ▸ 이론 결과",
        title: "논문형 결과",
        action: "「이론 결과」에서 초록형 요약을 봅니다",
        detail: "과정: 촉발 → 협상 → 재배치 → 안정/이탈.",
        shot: "./shots/b04-report.png", x: 8.5, y: 78, bubble: "right",
      },
      {
        n: "03",
        menu: "학습·설정 ▸ 절차형 실습",
        title: "절차형 실습",
        action: "「절차형 실습」매뉴얼로 체크리스트를 따라갑니다",
        detail: "자료수집 1-1부터 단계별로 익힙니다.",
        shot: "./shots/b02-practice.png", x: 8.5, y: 95, bubble: "right",
      },
      {
        n: "04",
        menu: "홈 ▸ 현재 진행",
        title: "진행 점검",
        action: "홈의 「현재 진행」에서 채움 상태를 확인합니다",
        detail: "모자란 단계를 보완한 뒤 내보내기로 넘어갑니다.",
        shot: "./shots/a06-progress.png", x: 40, y: 54, bubble: "top",
      },
      {
        n: "05",
        menu: "연구 절차 ▸ 이론 결과",
        title: "논문형 결과 확인",
        action: "「이론 결과」본문의 초록형 요약·과정을 확인합니다",
        detail: "핵심범주·과정(촉발→협상→재배치→안정/이탈)을 보고 산출물로 삼습니다.",
        shot: "./shots/b05-export.png", x: 52, y: 48, bubble: "left",
      },
    ],
    footer: "© Methodos Lab · methodosG 6",
  },
  en: {
    brand: "methodosG",
    kicker: "Desktop · Grounded theory v6",
    heroTitle: "Learn grounded theory with examples",
    introTitle: "About methodosG",
    introBody: [
      "methodosG is a desktop workbench for grounded-theory coding, categorizing, and theorizing.",
      "Open Example data (multicultural-family case), then follow Problem → Evidence → Meaning → Categories → Theory → Graphs → Theory results.",
      "Use Insert example text on each step, then apply the same menus to your project. Data stays offline on this PC.",
    ],
    pillars: [
      { title: "Example → coding", text: "Example · open · axial · selective" },
      { title: "Theory → report", text: "Graphs · results · export" },
      { title: "Local-first", text: "Offline storage" },
    ],
    ctaAnalyze: "Follow example → coding",
    ctaLearn: "Theory → report",
    shotNote: "Follow pin numbers on the real methodosG screen filled with example data.",
    clickHint: "Click here",
    analyzeSection: {
      eyebrow: "Core path A",
      title: "Example → coding",
      sub: "Example data → problem → evidence → meaning → categories → theory",
      play: "Play steps",
      pause: "Pause",
      replay: "Replay",
      menuLabel: "Menu",
    },
    learnSection: {
      eyebrow: "Core path B",
      title: "Theorizing → report",
      sub: "Graphs → theory results → practice → home progress → thesis results",
      play: "Play steps",
      pause: "Pause",
      replay: "Replay",
      menuLabel: "Menu",
    },
    analyzeSteps: [
      { n: "01", menu: "Example data", title: "Open examples", action: "Pick a case card under Example data", detail: "Start with a filled sample project.", shot: "./shots/a01-example.png", x: 8.5, y: 87, bubble: "right" },
      { n: "02", menu: "Home ▸ Learn with examples", title: "Start example flow", action: "Click Learn the flow with examples", detail: "Continue the example project from Home.", shot: "./shots/a00-home.png", x: 36, y: 31, bubble: "bottom" },
      { n: "03", menu: "Problem setting", title: "Problem sense", action: "Confirm the topic under Problem setting", detail: "Example: institutional use by multicultural families.", shot: "./shots/a00-problem.png", x: 8.5, y: 44, bubble: "right" },
      { n: "04", menu: "Evidence", title: "Source list", action: "Review the source matrix", detail: "Example: multi-site observation + stakeholder interviews.", shot: "./shots/a01-load.png", x: 8.5, y: 49.5, bubble: "right" },
      { n: "05", menu: "Meaning extraction", title: "Open coding", action: "Segment text and attach codes", detail: "Use Insert example text when needed.", shot: "./shots/a02-open.png", x: 8.5, y: 55, bubble: "right" },
      { n: "06", menu: "Category linking", title: "Axial coding", action: "Link focused codes into relations", detail: "Example codes: trigger · strategy · relocation.", shot: "./shots/a03-axial.png", x: 8.5, y: 60.5, bubble: "right" },
      { n: "07", menu: "Theory condensation", title: "Selective coding", action: "Lock the core category", detail: "Example core: local invention of practice.", shot: "./shots/a04-selective.png", x: 8.5, y: 66.5, bubble: "right" },
    ],
    learnSteps: [
      { n: "01", menu: "Result graphs", title: "Code frequency", action: "Open Result graphs", detail: "Inspect code bars from the example.", shot: "./shots/a05-graphs.png", x: 8.5, y: 72.5, bubble: "right" },
      { n: "02", menu: "Theory results", title: "Thesis-style results", action: "Open Theory results", detail: "Process: trigger → negotiate → relocate → settle/exit.", shot: "./shots/b04-report.png", x: 8.5, y: 78, bubble: "right" },
      { n: "03", menu: "Procedural practice", title: "Practice manual", action: "Follow the practice checklist", detail: "Start from data collection 1-1.", shot: "./shots/b02-practice.png", x: 8.5, y: 95, bubble: "right" },
      { n: "04", menu: "Home ▸ Progress", title: "Check progress", action: "Review fill status on Home", detail: "Fix gaps before export.", shot: "./shots/a06-progress.png", x: 40, y: 54, bubble: "top" },
      { n: "05", menu: "Theory results", title: "Review thesis-style results", action: "Check the abstract-style summary and process", detail: "Use core category and process as outputs.", shot: "./shots/b05-export.png", x: 52, y: 48, bubble: "left" },
    ],
    footer: "© Methodos Lab · methodosG 6",
  },
  zh: {
    brand: "methodosG",
    kicker: "Desktop · 扎根理论 v6",
    heroTitle: "用示例学习扎根理论工作台",
    introTitle: "methodosG 简介",
    introBody: [
      "methodosG 在桌面端按扎根理论的编码、范畴化与理论化程序引导操作。",
      "先打开「示例资料」（多文化家庭案例），再按问题设定 → 依据资料 → 意义提取 → 范畴连接 → 理论凝练 → 结果图 → 理论结果进行。",
      "各步骤可用「插入示例句子」查看填写示例，再用相同菜单做自己的项目。数据仅在本机离线处理。",
    ],
    pillars: [
      { title: "示例 → 编码", text: "示例·开放·轴心·选择" },
      { title: "理论化 → 报告", text: "图·结果·导出" },
      { title: "本地优先", text: "离线保存" },
    ],
    ctaAnalyze: "跟随示例 → 编码",
    ctaLearn: "理论化 → 报告",
    shotNote: "请跟随已填入示例资料的 methodosG 实际画面编号与字幕。",
    clickHint: "点击这里",
    analyzeSection: {
      eyebrow: "核心流程 A",
      title: "示例 → 编码",
      sub: "示例资料 → 问题设定 → 依据资料 → 意义提取 → 范畴连接 → 理论凝练",
      play: "播放步骤",
      pause: "暂停",
      replay: "重播",
      menuLabel: "菜单",
    },
    learnSection: {
      eyebrow: "核心流程 B",
      title: "理论化 → 报告",
      sub: "结果图 → 理论结果 → 程序练习 → 主页进度 → 论文型结果",
      play: "播放步骤",
      pause: "暂停",
      replay: "重播",
      menuLabel: "菜单",
    },
    analyzeSteps: [
      { n: "01", menu: "示例资料", title: "打开示例", action: "在「示例资料」选择案例卡片", detail: "先用填好的样本熟悉全流程。", shot: "./shots/a01-example.png", x: 8.5, y: 87, bubble: "right" },
      { n: "02", menu: "主页 ▸ 用示例学习流程", title: "开始示例流程", action: "点击「用示例学习流程」", detail: "从主页继续示例项目。", shot: "./shots/a00-home.png", x: 36, y: 31, bubble: "bottom" },
      { n: "03", menu: "问题设定", title: "问题感觉整理", action: "在「问题设定」确认主题", detail: "示例：多文化家庭制度使用经验形成。", shot: "./shots/a00-problem.png", x: 8.5, y: 44, bubble: "right" },
      { n: "04", menu: "依据资料", title: "资料源列表", action: "查看资料源矩阵", detail: "示例：多现场观察 + 利益相关者访谈。", shot: "./shots/a01-load.png", x: 8.5, y: 49.5, bubble: "right" },
      { n: "05", menu: "意义提取", title: "开放编码", action: "分节文本并附着代码", detail: "需要时可「插入示例句子」。", shot: "./shots/a02-open.png", x: 8.5, y: 55, bubble: "right" },
      { n: "06", menu: "范畴连接", title: "轴心编码", action: "把焦点代码连成关系", detail: "示例代码：条件_触发 · 策略_应对 · 结果_再配置。", shot: "./shots/a03-axial.png", x: 8.5, y: 60.5, bubble: "right" },
      { n: "07", menu: "理论凝练", title: "选择编码", action: "确定核心范畴", detail: "示例核心：实践的局部发明。", shot: "./shots/a04-selective.png", x: 8.5, y: 66.5, bubble: "right" },
    ],
    learnSteps: [
      { n: "01", menu: "结果图", title: "代码频率", action: "打开「结果图」", detail: "查看示例代码条形图。", shot: "./shots/a05-graphs.png", x: 8.5, y: 72.5, bubble: "right" },
      { n: "02", menu: "理论结果", title: "论文型结果", action: "打开「理论结果」", detail: "过程：触发 → 协商 → 再配置 → 稳定/离开。", shot: "./shots/b04-report.png", x: 8.5, y: 78, bubble: "right" },
      { n: "03", menu: "程序练习", title: "练习手册", action: "按练习清单推进", detail: "从资料收集 1-1 开始。", shot: "./shots/b02-practice.png", x: 8.5, y: 95, bubble: "right" },
      { n: "04", menu: "主页 ▸ 进度", title: "进度检查", action: "在主页查看完成度", detail: "补齐缺口后再导出。", shot: "./shots/a06-progress.png", x: 40, y: 54, bubble: "top" },
      { n: "05", menu: "理论结果", title: "确认论文型结果", action: "查看理论结果中的摘要与过程", detail: "把核心范畴与过程作为产出。", shot: "./shots/b05-export.png", x: 52, y: 48, bubble: "left" },
    ],
    footer: "© Methodos Lab · methodosG 6",
  },
};
